
ALTER TABLE tipo_proyecto ALTER COLUMN id_tipo_proyecto INT NOT NULL;
ALTER TABLE tipo_proyecto ALTER COLUMN nombre VARCHAR(50) NOT NULL;

ALTER TABLE proyecto ALTER COLUMN id_proyecto INT NOT NULL;
ALTER TABLE proyecto ALTER COLUMN nombre VARCHAR(50) NOT NULL;
ALTER TABLE proyecto ALTER COLUMN id_tipo_proyecto INT NOT NULL;

ALTER TABLE usuario ALTER COLUMN id_usuario INT NOT NULL;
ALTER TABLE usuario ALTER COLUMN nombre_usuario VARCHAR(30) NOT NULL;
ALTER TABLE usuario ALTER COLUMN apellido1_usuario VARCHAR(30) NOT NULL;

ALTER TABLE usuario ALTER COLUMN rol VARCHAR(50) NOT NULL;
ALTER TABLE usuario ALTER COLUMN permiso VARCHAR(50) NOT NULL;

ALTER TABLE programa ALTER COLUMN id_programa INT NOT NULL;
ALTER TABLE programa ALTER COLUMN facultad VARCHAR(50) NOT NULL;
ALTER TABLE programa ALTER COLUMN id_usuario INT NOT NULL;

ALTER TABLE docente ALTER COLUMN id_docente INT NOT NULL;
ALTER TABLE docente ALTER COLUMN id_asignatura INT NOT NULL;
ALTER TABLE docente ALTER COLUMN nombre_docente VARCHAR(16) NOT NULL;
ALTER TABLE docente ALTER COLUMN apellido_docente VARCHAR(16) NOT NULL;

ALTER TABLE asignatura ALTER COLUMN id_usuario INT NOT NULL;
ALTER TABLE asignatura ALTER COLUMN id_asignatura INT NOT NULL;
ALTER TABLE asignatura ALTER COLUMN nombre_asignatura VARCHAR(50) NOT NULL;
ALTER TABLE asignatura ALTER COLUMN id_docente INT NOT NULL;

ALTER TABLE programa_asignatura ALTER COLUMN id_programa INT NOT NULL;
ALTER TABLE programa_asignatura ALTER COLUMN id_asignatura INT NOT NULL;

ALTER TABLE rol ALTER COLUMN id_rol INT NOT NULL;
ALTER TABLE rol ALTER COLUMN nombre_rol VARCHAR(30) NOT NULL;

ALTER TABLE permiso ALTER COLUMN id_rol INT NOT NULL;
ALTER TABLE permiso ALTER COLUMN id_permiso INT NOT NULL;
ALTER TABLE permiso ALTER COLUMN tipo_permiso VARCHAR(16) NOT NULL;

ALTER TABLE estudiante ALTER COLUMN id_usuario INT NOT NULL;
ALTER TABLE estudiante ALTER COLUMN id_programa INT NOT NULL;
ALTER TABLE estudiante ALTER COLUMN id_asignatura INT NOT NULL;
ALTER TABLE estudiante ALTER COLUMN codigo_grupo VARCHAR(16) NOT NULL;

ALTER TABLE entregable ALTER COLUMN id_proyecto INT NOT NULL;
ALTER TABLE entregable ALTER COLUMN id_entregable INT NOT NULL;
ALTER TABLE entregable ALTER COLUMN nombre_entregable VARCHAR(50) NOT NULL;

ALTER TABLE tipo_entregable ALTER COLUMN id_tipo_entregable INT NOT NULL;
ALTER TABLE tipo_entregable ALTER COLUMN id_entregable INT NOT NULL;
ALTER TABLE tipo_entregable ALTER COLUMN id_proyecto INT NOT NULL;
ALTER TABLE tipo_entregable ALTER COLUMN nombre_tipo VARCHAR(30) NOT NULL;

ALTER TABLE ira ALTER COLUMN id_usuario INT NOT NULL;
ALTER TABLE ira ALTER COLUMN id_proyecto INT NOT NULL;
ALTER TABLE ira ALTER COLUMN indice VARCHAR(50) NOT NULL;
ALTER TABLE ira ALTER COLUMN id_asignatura INT NOT NULL;
ALTER TABLE ira ALTER COLUMN id_docente INT NOT NULL;

ALTER TABLE evaluacion ALTER COLUMN id_evaluacion INT NOT NULL;
ALTER TABLE evaluacion ALTER COLUMN id_evaluador INT NOT NULL;
ALTER TABLE evaluacion ALTER COLUMN nota_evaluacion INT NOT NULL;

ALTER TABLE rep ALTER COLUMN id_rep INT NOT NULL;
ALTER TABLE rep ALTER COLUMN resultado VARCHAR(16) NOT NULL;

ALTER TABLE material ALTER COLUMN id_proyecto INT NOT NULL;
ALTER TABLE material ALTER COLUMN id_material INT NOT NULL;
ALTER TABLE material ALTER COLUMN material VARCHAR(50) NOT NULL;
